/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ServiceType = IDL.Variant({
  'destinationWedding' : IDL.Null,
  'bridalPortrait' : IDL.Null,
  'candidPhotography' : IDL.Null,
  'weddingPhotography' : IDL.Null,
  'preWeddingShoot' : IDL.Null,
  'cinematicFilm' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'weddingDate' : Time,
  'serviceType' : ServiceType,
  'message' : IDL.Text,
  'timestamp' : Time,
  'coupleNames' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, Time, IDL.Text, ServiceType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ServiceType = IDL.Variant({
    'destinationWedding' : IDL.Null,
    'bridalPortrait' : IDL.Null,
    'candidPhotography' : IDL.Null,
    'weddingPhotography' : IDL.Null,
    'preWeddingShoot' : IDL.Null,
    'cinematicFilm' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'weddingDate' : Time,
    'serviceType' : ServiceType,
    'message' : IDL.Text,
    'timestamp' : Time,
    'coupleNames' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, Time, IDL.Text, ServiceType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };